from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path


GENERATED_RELATIVE_PATH = "port/src/generated/reference_metadata.zig"


@dataclass(frozen=True)
class EntryMetadata:
    entry_index: int
    entry_type: str | None
    entry_description: str | None


@dataclass(frozen=True)
class GameStateFlag:
    index: int
    display_name: str


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Generate checked-in reference metadata overlays from the local LBALab metadata clone."
    )
    parser.add_argument(
        "--metadata-root",
        default=str(repo_root.parent / "lba-reference-repos" / "metadata"),
        help="Path to the cloned LBALab metadata repository root.",
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / GENERATED_RELATIVE_PATH),
        help="Path to the generated Zig module.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate that the generated Zig module already matches the local LBALab metadata clone.",
    )
    return parser.parse_args()


def zig_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_entry_metadata(path: Path) -> list[EntryMetadata]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    entries = payload.get("entries")
    if not isinstance(entries, list):
        raise ValueError(f"{path} is missing a list-valued entries field")

    result: list[EntryMetadata] = []
    for index, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict):
            continue
        entry_type = entry.get("type")
        entry_description = entry.get("description")
        result.append(
            EntryMetadata(
                entry_index=index,
                entry_type=entry_type if isinstance(entry_type, str) and entry_type else None,
                entry_description=entry_description if isinstance(entry_description, str) and entry_description else None,
            )
        )
    return result


def load_game_state_flags(path: Path) -> dict[int, GameStateFlag]:
    flags: dict[int, GameStateFlag] = {}
    pattern = re.compile(r"^\s*(\d+):\s*(.*)$")
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(raw_line)
        if not match:
            continue
        if raw_line.startswith("      "):
            continue
        index = int(match.group(1))
        display_name = match.group(2).strip()
        flags[index] = GameStateFlag(index=index, display_name=display_name)
    return flags


def render_entry_array(entries: list[EntryMetadata]) -> str:
    lines: list[str] = []
    for entry in entries:
        entry_type = "null" if entry.entry_type is None else zig_quote(entry.entry_type)
        entry_description = "null" if entry.entry_description is None else zig_quote(entry.entry_description)
        lines.extend(
            (
                "    .{",
                f"        .entry_index = {entry.entry_index},",
                f"        .entry_type = {entry_type},",
                f"        .entry_description = {entry_description},",
                "    },",
            )
        )
    return "\n".join(lines)


def render_flag(name: str, flag: GameStateFlag) -> str:
    return "\n".join(
        (
            f"pub const {name} = GameStateFlag" + "{",
            f"    .index = {flag.index},",
            f"    .display_name = {zig_quote(flag.display_name)},",
            "};",
        )
    )


def render_module(
    body_entries: list[EntryMetadata],
    xx_gam_entries: list[EntryMetadata],
    sendell_ball_flag: GameStateFlag,
    lightning_spell_flag: GameStateFlag,
) -> str:
    return f"""// Generated by tools/generate_reference_metadata.py.
// Do not edit by hand; regenerate from the local LBALab metadata clone.

pub const generated_relative_path = "{GENERATED_RELATIVE_PATH}";
pub const body_hqr_upstream_relative_path = "../lba-reference-repos/metadata/LBA2/HQR/BODY.HQR.json";
pub const xx_gam_vox_upstream_relative_path = "../lba-reference-repos/metadata/LBA2/HQR/VOX/XX_GAM.VOX.json";
pub const state_flags_upstream_relative_path = "../lba-reference-repos/metadata/LBA2/GAME_STATE_FLAGS/STATE_FLAGS.md";

pub const EntryMetadata = struct {{
    entry_index: usize,
    entry_type: ?[]const u8,
    entry_description: ?[]const u8,
}};

pub const GameStateFlag = struct {{
    index: u8,
    display_name: []const u8,
}};

pub const body_hqr_entries: []const EntryMetadata = &.{{
{render_entry_array(body_entries)}
}};

pub const xx_gam_vox_entries: []const EntryMetadata = &.{{
{render_entry_array(xx_gam_entries)}
}};

{render_flag("sendell_ball_flag", sendell_ball_flag)}

{render_flag("lightning_spell_flag", lightning_spell_flag)}
"""


def build_rendered_module(metadata_root: Path) -> str:
    body_entries = load_entry_metadata(metadata_root / "LBA2" / "HQR" / "BODY.HQR.json")
    xx_gam_entries = load_entry_metadata(metadata_root / "LBA2" / "HQR" / "VOX" / "XX_GAM.VOX.json")
    flags = load_game_state_flags(metadata_root / "LBA2" / "GAME_STATE_FLAGS" / "STATE_FLAGS.md")

    return render_module(
        body_entries=body_entries,
        xx_gam_entries=xx_gam_entries,
        sendell_ball_flag=flags[3],
        lightning_spell_flag=flags[19],
    )


def write_or_check_output(rendered: str, output_path: Path, *, check: bool) -> int:
    if check:
        if not output_path.exists():
            print(f"reference metadata drift: missing generated file at {output_path}")
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                "reference metadata drift detected; run "
                f"py -3 tools/generate_reference_metadata.py --output {output_path}"
            )
            return 1
        print(f"reference metadata is up to date: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote reference metadata to {output_path}")
    return 0


def main() -> int:
    args = parse_args()
    metadata_root = Path(args.metadata_root)
    output_path = Path(args.output)

    if not metadata_root.exists():
        raise FileNotFoundError(f"metadata root not found: {metadata_root}")

    rendered = build_rendered_module(metadata_root)
    return write_or_check_output(rendered, output_path, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
